name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint_and_test:
    name: Run linter and tests
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - run: npm ci
      - run: npm run lint
      - run: npm test
